/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BwaJni */

#ifndef _Included_com_github_sparkbwa_BwaJni
#define _Included_com_github_sparkbwa_BwaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BwaJni
 * Method:    runBwbble
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_sparkbwa_BwaJni_runBwbble
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
